//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtmaisBackend.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareLinkMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareLinkMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtmaisBackend.Infrastructure.ShareLinkMessages", typeof(ShareLinkMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Olá,+gostaria+de+conversar+sobre+a+sua+arte+disponível+na+plataforma+Art%2B..
        /// </summary>
        public static string MessageComunication {
            get {
                return ResourceManager.GetString("MessageComunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %20Olhá%20só%20que%20publicação%20incrivel%20que%20eu%20achei%20na%20plataforma%20Art%2B..
        /// </summary>
        public static string MessageShareComment {
            get {
                return ResourceManager.GetString("MessageShareComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %20Olhá%20só%20que%20perfil%20incrivel%20que%20eu%20achei%20na%20plataforma%20Art%2B..
        /// </summary>
        public static string MessageShareLink {
            get {
                return ResourceManager.GetString("MessageShareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %20Este%20é%20meu%20perfil%20na%20Plataforma%20Art%2B,%20visite-o%20para%20conhecer%20o%20meu%20trabalho..
        /// </summary>
        public static string MessageShareProfile {
            get {
                return ResourceManager.GetString("MessageShareProfile", resourceCulture);
            }
        }
    }
}
